name: Recent Activity
on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch:
permissions:
  contents: write
jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          COMMIT_MSG: "chore: update recent activity"
          MAX_LINES: 10
